#define NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE 64
#define NETSTACK_CONF_RDC nullrdc_driver

#define NULLRDC_802154_AUTOACK 1
#define NULLRDC_802154_AUTOACK_HW 1
#define RPL_MAX_PARENTS_PER_DAG 10
#define RPL_CONF_DAO_ACK 1
/*#define WITH_COMPOWER 0*/
#define PROCESS_CONF_NO_PROCESS_NAMES 1

#define UIP_CONF_TCP 1

/*smart-HOP Configurations*/
#define MOBILE_NODE 1
#define RPL_CONF_LEAF_ONLY 1
#define MN_CONNECTION 0
#define NULLRDC_SEND_802154_ACK 1
